### ISSUE TITLE
install  error

### ISSUE THREAD

**Issue by Osub** [latticexyz/opcraft#67]
```
Error: Couldn't find package "swarm-js@^0.1.40" required by "web3-bzz@1.8.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "nofilter@^1.0.4" required by "cbor@^5.2.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "web3-eth-contract@1.8.1" required by "web3-eth@1.8.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "got@12.1.0" required by "web3-bzz@1.8.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "memorystream@^0.3.1" required by "solc@^0.4.20" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "yargs@^4.7.1" required by "solc@^0.4.20" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "rimraf@^2.2.8" required by "fs-extra@^0.30.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "require-from-string@^1.1.0" required by "solc@^0.4.20" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "web3-eth-abi@1.8.1" required by "web3-eth@1.8.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "web3-eth-contract@1.8.1" required by "web3-eth-ens@1.8.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "web3-providers-ws@1.8.1" required by "web3-core-requestmanager@1.8.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "web3-eth-abi@1.8.1" required by "web3-eth-ens@1.8.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "util@^0.12.0" required by "web3-core-requestmanager@1.8.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/nft/.nvm/versions/node/v16.15.1/lib/node_modules/yarn/lib/cli.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by claudioantonio** [comment]
@Osub are you still having this problem?
What is your OS and its version?
